import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  async function handleOnSubmit(e) {
    e.preventDefault();
    const formData = {}
    Array.from(e.currentTarget.elements).forEach(field => {
      if (!field.name) return;
      formData[field.name] = field.value;
    });
    fetch('/api/mail', {
      method: 'post',
      body: JSON.stringify(formData)
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          SendGrid Email form
        </h1>

        <div className={styles.grid}>
          <form method='post' onSubmit={handleOnSubmit}>
            <p className={styles.row}>
              <label htmlFor='name'>Name:</label>
              <input type="text" name="name" />
            </p>
            <p className={styles.row}>
              <label htmlFor='email'>Email:</label>
              <input type="email" name="email" />
            </p>
            <p className={styles.row}>
              <label htmlFor='message'>Message:</label>
              <textarea name="message" rows={4} />
            </p>
            <p className={styles.rowButtons}>
              <button type='submit'>Send 📨</button>
            </p>
          </form>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
